### ISSUE TITLE
The `errorIfUnknownCommand` does not work as expected with `defaultCommand` 

### ISSUE THREAD

**Issue by wickedest** [cb1kenobi/cli-kit#96]
I am trying to make a hidden default command called "upgrade", so I created a CLI:
```js
	return new CLI({
		name: pkg.name,
		version: pkg.version,
		help: true,
		helpExitCode: 2,
		banner: chalk.cyan(`API Builder OpenAPI upgrade, version ${pkg.version}`),
		options: {
			'--no-install': 'Do not automatically install dependencies using npm.',
			'--debug': 'Enable debug logging',
			'--cwd': {
				desc: 'Use the `process.cwd` for the project directory to upgrade.',
				hidden: true
			}
		},
		defaultCommand: 'upgrade',
		errorIfUnknownCommand: true,
		commands: {
			'upgrade': {
				hidden: true,
				action: async ({ argv, _ }) => {
					await runUpgrade.run(argv);
				}
			}
		}
	});
```

When there is a `defaultCommand`, supplying an unknown command fails to trigger the "Unknown command" error. I think the `defaultCommand` should only be used if no command was provided.  If an invalid command was provided, it should error.

**Comment by cb1kenobi** [comment]
I'll investigate, stay tuned!

**Comment by cb1kenobi** [comment]
OK, so here's the problem. If you run "mycli foo", it will look for a command "foo" which does not exist. It then treats "foo" as an unknown argument.

After the parsing is complete, it will determine there was no command found and execute the default command (e.g. upgrade) and pass in the parsed unknown arguments.

Since cli-kit allows unknown arguments, it can't suggest the command is unknown. That would be a breaking change.

For cli-kit v2, I was going to rewrite the parser such that any unknown command, option, or argument would throw. This is also a breaking change, but it would fix a bunch of headaches like misspelled options. It also solves another problem where "axway bar" and "axway foo bar" are the same command, just that "foo" becomes an unknown argument to the "bar" command. Not allowing unknown arguments between known commands would solve this.

**Comment by wickedest** [comment]
Thanks @cb1kenobi. I worked around it by handling the unknown argument myself.  You might not need a v2 if there is an option to toggle strict arguments (false by default), but it may be harder to do so. Thanks!

**Comment by cb1kenobi** [comment]
I'll see what I can do. There will be a v2 because we are migrating cli-kit to an ES module.
